"""Product-specific models for Planning Center API."""

from .calendar import (
    PCOCalendarEvent,
    PCOEventAttachment,
    PCOEventInstance,
    PCOEventLabel,
    PCOEventNote,
    PCOEventRsvp,
    PCOEventTime,
)
from .check_ins import (
    PCOCheckIn,
    PCOCheckInHousehold,
    PCOCheckInPerson,
    PCOEvent,
    PCOLocation,
    PCOStation,
)
from .giving import (
    PCOBatch,
    PCODesignation,
    PCODonation,
    PCOFund,
    PCOPledge,
    PCORecurringDonation,
)
from .groups import (
    PCOGroup,
    PCOGroupMembership,
    PCOGroupNote,
    PCOGroupTime,
    PCOGroupType,
)
from .people import (
    PCOAddress,
    PCOCustomField,
    PCOEmail,
    PCOFieldData,
    PCOHousehold,
    PCOInactiveReason,
    PCOMaritalStatus,
    PCONameSuffix,
    PCONameTitle,
    PCOPerson,
    PCOPhoneNumber,
    PCOWorkflow,
    PCOWorkflowStep,
)
from .registrations import (
    PCORegistration,
    PCORegistrationEvent,
    PCORegistrationEventInstance,
    PCORegistrationEventTime,
    PCORegistrationForm,
    PCORegistrationFormField,
    PCORegistrationFormFieldOption,
    PCORegistrationInstance,
    PCORegistrationInstancePerson,
    PCORegistrationInstancePersonAnswer,
)
from .services import (
    PCOArrangement,
    PCOAttachment,
    PCOFolder,
    PCOKey,
    PCOMedia,
    PCOPlan,
    PCOPlanNote,
    PCOPlanPerson,
    PCOPlanTime,
    PCOService,
    PCOServiceType,
    PCOSong,
    PCOTemplate,
)

__all__ = [
    # People
    "PCOPerson",
    "PCOEmail",
    "PCOPhoneNumber",
    "PCOAddress",
    "PCOFieldData",
    "PCOCustomField",
    "PCOHousehold",
    "PCOInactiveReason",
    "PCOMaritalStatus",
    "PCONameSuffix",
    "PCONameTitle",
    "PCOWorkflow",
    "PCOWorkflowStep",
    # Services
    "PCOService",
    "PCOServiceType",
    "PCOPlan",
    "PCOPlanTime",
    "PCOPlanPerson",
    "PCOPlanNote",
    "PCOSong",
    "PCOArrangement",
    "PCOKey",
    "PCOAttachment",
    "PCOMedia",
    "PCOFolder",
    "PCOTemplate",
    # Check-Ins
    "PCOEvent",
    "PCOLocation",
    "PCOStation",
    "PCOCheckIn",
    "PCOCheckInPerson",
    "PCOCheckInHousehold",
    # Giving
    "PCODonation",
    "PCOFund",
    "PCOBatch",
    "PCODesignation",
    "PCOPledge",
    "PCORecurringDonation",
    # Groups
    "PCOGroup",
    "PCOGroupType",
    "PCOGroupTime",
    "PCOGroupMembership",
    "PCOGroupNote",
    # Calendar
    "PCOCalendarEvent",
    "PCOEventInstance",
    "PCOEventTime",
    "PCOEventRsvp",
    "PCOEventNote",
    "PCOEventLabel",
    "PCOEventAttachment",
    # Registrations
    "PCORegistrationEvent",
    "PCORegistrationEventInstance",
    "PCORegistrationEventTime",
    "PCORegistration",
    "PCORegistrationForm",
    "PCORegistrationFormField",
    "PCORegistrationFormFieldOption",
    "PCORegistrationInstance",
    "PCORegistrationInstancePerson",
    "PCORegistrationInstancePersonAnswer",
]
